# -- Main Menu --

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 10

[[main]]
  name = "Docs"
  pageRef = "docs"
  weight = 20

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 30

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/popz2049-afk"
  weight = 100

# -- Footer Menu --

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 20
