colorScheme = "zscaler"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = true

mainSections = ["blog"]

disableImageOptimization = false
disableTextInHeader = false

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = true

[header]
  layout = "fixed-fill-blur"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "hero"
  homepageImage = "img/hero.svg"
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "blog"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateUpdated = true
  showAuthor = true
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true
  showAuthorsBadges = true
  showWordCount = false
  sharingLinks = ["linkedin", "twitter", "reddit", "email"]
  showZenMode = true

[list]
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  showBreadcrumbs = true
  showSummary = true
  showTableOfContents = false
  showCards = true
  orderByWeight = false
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = false
  cardView = true

[term]
  showHero = true
  heroStyle = "background"
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
